[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
cmds = ["node apps/api/scripts/build-bundle.js"]

[start]
cmd = "node apps/api/dist-bundle/main.js"
