[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && node apps/api/scripts/build-bundle.js && node apps/api/scripts/build-seed.js"

[deploy]
startCommand = "node apps/api/dist-bundle/main.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/health"
healthcheckTimeout = 300

# Deploy trigger: Sun Apr 26 21:49:10 EAST 2026
