import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateActivityLogsTable1771670994624 implements MigrationInterface {
    name = 'CreateActivityLogsTable1771670994624'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_owner_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_portfolio_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "projects_program_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "programs_owner_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "programs_portfolio_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "portfolios_owner_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" DROP CONSTRAINT "fk_wpr_from"`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" DROP CONSTRAINT "fk_wpr_to"`);
        await queryRunner.query(`ALTER TABLE "work_package_watchers" DROP CONSTRAINT "fk_wpw_user"`);
        await queryRunner.query(`ALTER TABLE "work_package_watchers" DROP CONSTRAINT "fk_wpw_work_package"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "fk_work_packages_assignee"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "fk_work_packages_accountable"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "fk_work_packages_project"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "fk_work_packages_parent"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "FK_71743212b396e38a37c4ec09369"`);
        await queryRunner.query(`ALTER TABLE "baseline_work_packages" DROP CONSTRAINT "fk_bwp_baseline"`);
        await queryRunner.query(`ALTER TABLE "baselines" DROP CONSTRAINT "fk_baselines_creator"`);
        await queryRunner.query(`ALTER TABLE "baselines" DROP CONSTRAINT "fk_baselines_project"`);
        await queryRunner.query(`ALTER TABLE "board_columns" DROP CONSTRAINT "fk_board_columns_board"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "fk_boards_project"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "fk_time_entries_user"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "fk_time_entries_work_package"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "fk_comments_user"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "fk_comments_parent"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_role_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "role_permissions_permission_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_group_members" DROP CONSTRAINT "user_group_members_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_group_members" DROP CONSTRAINT "user_group_members_group_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "user_roles_role_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_program"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_portfolio"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_owner"`);
        await queryRunner.query(`DROP INDEX "public"."idx_projects_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_programs_portfolio"`);
        await queryRunner.query(`DROP INDEX "public"."idx_programs_owner"`);
        await queryRunner.query(`DROP INDEX "public"."idx_portfolios_owner"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wpr_from"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wpr_to"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sprints_project"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sprints_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wp_project"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wp_assignee"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wp_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wp_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_wp_dates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_work_calendars_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_work_calendars_is_default"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bwp_baseline"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bwp_work_package"`);
        await queryRunner.query(`DROP INDEX "public"."idx_baselines_project"`);
        await queryRunner.query(`DROP INDEX "public"."idx_board_columns_board"`);
        await queryRunner.query(`DROP INDEX "public"."idx_board_columns_position"`);
        await queryRunner.query(`DROP INDEX "public"."idx_boards_project"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sprint_burndown_sprint"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sprint_burndown_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sprint_burndown_sprint_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_time_wp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_time_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_time_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comments_entity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comments_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comments_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_comments_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_role_permissions_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_role_permissions_permission"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_group_members_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_group_members_group"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "valid_status"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "valid_status"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "valid_phase"`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" DROP CONSTRAINT "no_self_relation"`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" DROP CONSTRAINT "valid_relation"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "valid_sprint_status"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "valid_sprint_dates"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "work_packages_progress_percent_check"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "valid_type"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "valid_priority"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "valid_scheduling"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "valid_board_type"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "time_entries_hours_check"`);
        await queryRunner.query(`CREATE TYPE "public"."cost_entries_type_enum" AS ENUM('labor', 'material', 'equipment', 'subcontractor', 'other')`);
        await queryRunner.query(`CREATE TABLE "cost_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workPackageId" uuid NOT NULL, "userId" uuid, "type" "public"."cost_entries_type_enum" NOT NULL DEFAULT 'other', "amount" numeric(12,2) NOT NULL, "description" text, "date" date NOT NULL, "reference" text, "billable" boolean NOT NULL DEFAULT false, "currency" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f6bc78f0721ef21e37905a1b156" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b0d1a12bb5e099d982b5e14266" ON "cost_entries" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_72bf9076541377ad54db20a359" ON "cost_entries" ("userId", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_22bd6c46545bb03821d08f282c" ON "cost_entries" ("workPackageId", "date") `);
        await queryRunner.query(`CREATE TABLE "budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "name" text NOT NULL, "totalBudget" numeric(12,2) NOT NULL, "currency" text, "startDate" date NOT NULL, "endDate" date NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "breakdown" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0441d95918d17f347cef513b9e" ON "budgets" ("projectId") `);
        await queryRunner.query(`CREATE TYPE "public"."activity_logs_actiontype_enum" AS ENUM('CREATED', 'UPDATED', 'DELETED', 'COMMENTED', 'ATTACHED', 'MENTIONED', 'TRANSITIONED', 'ASSIGNED', 'SHARED')`);
        await queryRunner.query(`CREATE TYPE "public"."activity_logs_entitytype_enum" AS ENUM('Project', 'WorkPackage', 'TimeEntry', 'CostEntry', 'Comment', 'Attachment', 'WikiPage', 'Sprint', 'Board', 'Baseline')`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "projectId" uuid NOT NULL, "workPackageId" uuid, "userId" uuid NOT NULL, "actionType" "public"."activity_logs_actiontype_enum" NOT NULL, "entityType" "public"."activity_logs_entitytype_enum" NOT NULL, "entityId" uuid NOT NULL, "description" text NOT NULL, "metadata" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a3d5764d4b44970698381dc664" ON "activity_logs" ("entityType") `);
        await queryRunner.query(`CREATE INDEX "IDX_23c3961f60f0d66110d6b292ed" ON "activity_logs" ("actionType") `);
        await queryRunner.query(`CREATE INDEX "IDX_412f03f2a073c89f8918e6ae52" ON "activity_logs" ("userId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_66181ab26ce83746f858e62c34" ON "activity_logs" ("projectId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "work_package_relations" ALTER COLUMN "lag_days" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "created_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "updated_at" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "work_packages" ALTER COLUMN "spent_hours" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_packages" ALTER COLUMN "progress_percent" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_calendars" ALTER COLUMN "working_days" SET DEFAULT '[1,2,3,4,5]'`);
        await queryRunner.query(`ALTER TABLE "work_calendars" ALTER COLUMN "working_hours" SET DEFAULT '{"startHour":8,"startMinute":0,"endHour":17,"endMinute":0}'`);
        await queryRunner.query(`ALTER TABLE "work_calendars" ALTER COLUMN "holidays" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "billable" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "entity_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "mentions" SET DEFAULT '[]'`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_3774bdecd0da2962ed2228fa6e" ON "projects" ("program_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2a7c763195dbbcd4e22c06266" ON "projects" ("portfolio_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b1bd2fbf5d0ef67319c91acb5c" ON "projects" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a27865a7be17886e3088f4a650" ON "projects" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3edb22630d795d2fade336b7e2" ON "programs" ("portfolio_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3a550c8827bb78d804292ef5a" ON "programs" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_69989f25bb9a0dbb2c261675d2" ON "portfolios" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a068a527d26f32b85b20277da6" ON "work_package_relations" ("from_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6a883862a25d84a9685230a484" ON "work_package_relations" ("to_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_82145010051f3f2fc94671c0b3" ON "sprints" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_36abc1836392c93502ff1a16e3" ON "sprints" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d90a41210e04a637029b51a96b" ON "work_packages" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_41c18baf1970fb81c6f4a35191" ON "work_packages" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a25f9a3be462d724136d1e1b3" ON "work_packages" ("assignee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d77734f3766fe056c7f1ffc02b" ON "work_packages" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aaaaa9a77a890a5c36d2b515fe" ON "work_calendars" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff9cf4ac0f2e53dabcc2bcffe8" ON "work_calendars" ("is_default") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b6e2de4d72341fb6e613e2a0a" ON "baseline_work_packages" ("baseline_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_99babf97daa6524238d8d162ec" ON "baseline_work_packages" ("work_package_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7049e9169a39f27abae7da9f5" ON "baselines" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_55e6772f5b84a2fb358db47331" ON "board_columns" ("board_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1542ae826c0dfeaf4c79e07fc5" ON "boards" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_595e51941bab1e8bfde9f653ca" ON "sprint_burndown" ("sprint_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_738fef438faf1a42a78cff7a3c" ON "sprint_burndown" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_cba257b1f2ca02409e4546412c" ON "time_entries" ("work_package_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f16c3c269283ee42429d09d693" ON "time_entries" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3109c0f4f5d3dc2633664a919" ON "time_entries" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_32ba1d353e99d14130486cd34c" ON "user_group_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ff9c9893bced1f20a11c992c1" ON "user_group_members" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "sprint_burndown" ADD CONSTRAINT "UQ_239995a6c3abe889dac3f08062e" UNIQUE ("sprint_id", "date")`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_3774bdecd0da2962ed2228fa6ef" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_c2a7c763195dbbcd4e22c062669" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "FK_3edb22630d795d2fade336b7e2d" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "FK_a3a550c8827bb78d804292ef5ac" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "FK_69989f25bb9a0dbb2c261675d20" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" ADD CONSTRAINT "FK_a068a527d26f32b85b20277da60" FOREIGN KEY ("from_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" ADD CONSTRAINT "FK_6a883862a25d84a9685230a4847" FOREIGN KEY ("to_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_package_watchers" ADD CONSTRAINT "FK_049d6b7fc5be71c60070c795bc5" FOREIGN KEY ("work_package_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_package_watchers" ADD CONSTRAINT "FK_de72012dc57ef5771737cd7b1a9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "FK_d90a41210e04a637029b51a96b8" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "FK_7a25f9a3be462d724136d1e1b34" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "FK_389f5b44644a737eaa268a15161" FOREIGN KEY ("accountable_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "FK_d77734f3766fe056c7f1ffc02b0" FOREIGN KEY ("parent_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "FK_71743212b396e38a37c4ec09369" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "baseline_work_packages" ADD CONSTRAINT "FK_4b6e2de4d72341fb6e613e2a0ac" FOREIGN KEY ("baseline_id") REFERENCES "baselines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "baselines" ADD CONSTRAINT "FK_f7049e9169a39f27abae7da9f5c" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "baselines" ADD CONSTRAINT "FK_7fc3428e4c8637f74b8b509e06c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "board_columns" ADD CONSTRAINT "FK_55e6772f5b84a2fb358db473313" FOREIGN KEY ("board_id") REFERENCES "boards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_1542ae826c0dfeaf4c79e07fc57" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_cba257b1f2ca02409e4546412ca" FOREIGN KEY ("work_package_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "FK_f16c3c269283ee42429d09d693d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_entries" ADD CONSTRAINT "FK_71200964b0e2a95482b0031521a" FOREIGN KEY ("workPackageId") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cost_entries" ADD CONSTRAINT "FK_519facb547d17bc4df81d9f4ec8" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budgets" ADD CONSTRAINT "FK_0441d95918d17f347cef513b9e4" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d9164fd61b6f08f6068e9c542ea" FOREIGN KEY ("projectId") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d8c4c4f6ab07d0cbe6c4495282e" FOREIGN KEY ("workPackageId") REFERENCES "work_packages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_597e6df96098895bf19d4b5ea45" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_d6f93329801a93536da4241e386" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_group_members" ADD CONSTRAINT "FK_32ba1d353e99d14130486cd34cf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_group_members" ADD CONSTRAINT "FK_0ff9c9893bced1f20a11c992c16" FOREIGN KEY ("group_id") REFERENCES "user_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "user_group_members" DROP CONSTRAINT "FK_0ff9c9893bced1f20a11c992c16"`);
        await queryRunner.query(`ALTER TABLE "user_group_members" DROP CONSTRAINT "FK_32ba1d353e99d14130486cd34cf"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_d6f93329801a93536da4241e386"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_597e6df96098895bf19d4b5ea45"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d8c4c4f6ab07d0cbe6c4495282e"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d9164fd61b6f08f6068e9c542ea"`);
        await queryRunner.query(`ALTER TABLE "budgets" DROP CONSTRAINT "FK_0441d95918d17f347cef513b9e4"`);
        await queryRunner.query(`ALTER TABLE "cost_entries" DROP CONSTRAINT "FK_519facb547d17bc4df81d9f4ec8"`);
        await queryRunner.query(`ALTER TABLE "cost_entries" DROP CONSTRAINT "FK_71200964b0e2a95482b0031521a"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_f16c3c269283ee42429d09d693d"`);
        await queryRunner.query(`ALTER TABLE "time_entries" DROP CONSTRAINT "FK_cba257b1f2ca02409e4546412ca"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_1542ae826c0dfeaf4c79e07fc57"`);
        await queryRunner.query(`ALTER TABLE "board_columns" DROP CONSTRAINT "FK_55e6772f5b84a2fb358db473313"`);
        await queryRunner.query(`ALTER TABLE "baselines" DROP CONSTRAINT "FK_7fc3428e4c8637f74b8b509e06c"`);
        await queryRunner.query(`ALTER TABLE "baselines" DROP CONSTRAINT "FK_f7049e9169a39f27abae7da9f5c"`);
        await queryRunner.query(`ALTER TABLE "baseline_work_packages" DROP CONSTRAINT "FK_4b6e2de4d72341fb6e613e2a0ac"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "FK_71743212b396e38a37c4ec09369"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "FK_d77734f3766fe056c7f1ffc02b0"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "FK_389f5b44644a737eaa268a15161"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "FK_7a25f9a3be462d724136d1e1b34"`);
        await queryRunner.query(`ALTER TABLE "work_packages" DROP CONSTRAINT "FK_d90a41210e04a637029b51a96b8"`);
        await queryRunner.query(`ALTER TABLE "work_package_watchers" DROP CONSTRAINT "FK_de72012dc57ef5771737cd7b1a9"`);
        await queryRunner.query(`ALTER TABLE "work_package_watchers" DROP CONSTRAINT "FK_049d6b7fc5be71c60070c795bc5"`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" DROP CONSTRAINT "FK_6a883862a25d84a9685230a4847"`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" DROP CONSTRAINT "FK_a068a527d26f32b85b20277da60"`);
        await queryRunner.query(`ALTER TABLE "portfolios" DROP CONSTRAINT "FK_69989f25bb9a0dbb2c261675d20"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "FK_a3a550c8827bb78d804292ef5ac"`);
        await queryRunner.query(`ALTER TABLE "programs" DROP CONSTRAINT "FK_3edb22630d795d2fade336b7e2d"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_b1bd2fbf5d0ef67319c91acb5cf"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_c2a7c763195dbbcd4e22c062669"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_3774bdecd0da2962ed2228fa6ef"`);
        await queryRunner.query(`ALTER TABLE "sprint_burndown" DROP CONSTRAINT "UQ_239995a6c3abe889dac3f08062e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ff9c9893bced1f20a11c992c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32ba1d353e99d14130486cd34c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3109c0f4f5d3dc2633664a919"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f16c3c269283ee42429d09d693"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cba257b1f2ca02409e4546412c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_738fef438faf1a42a78cff7a3c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_595e51941bab1e8bfde9f653ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1542ae826c0dfeaf4c79e07fc5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55e6772f5b84a2fb358db47331"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7049e9169a39f27abae7da9f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99babf97daa6524238d8d162ec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b6e2de4d72341fb6e613e2a0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff9cf4ac0f2e53dabcc2bcffe8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aaaaa9a77a890a5c36d2b515fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d77734f3766fe056c7f1ffc02b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a25f9a3be462d724136d1e1b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41c18baf1970fb81c6f4a35191"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d90a41210e04a637029b51a96b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36abc1836392c93502ff1a16e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82145010051f3f2fc94671c0b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a883862a25d84a9685230a484"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a068a527d26f32b85b20277da6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69989f25bb9a0dbb2c261675d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3a550c8827bb78d804292ef5a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3edb22630d795d2fade336b7e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a27865a7be17886e3088f4a650"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1bd2fbf5d0ef67319c91acb5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2a7c763195dbbcd4e22c06266"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3774bdecd0da2962ed2228fa6e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "mentions" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "entity_type"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "entity_type" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "time_entries" ALTER COLUMN "billable" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_calendars" ALTER COLUMN "holidays" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_calendars" ALTER COLUMN "working_hours" SET DEFAULT '{"endHour": 17, "endMinute": 0, "startHour": 8, "startMinute": 0}'`);
        await queryRunner.query(`ALTER TABLE "work_calendars" ALTER COLUMN "working_days" SET DEFAULT '[1, 2, 3, 4, 5]'`);
        await queryRunner.query(`ALTER TABLE "work_packages" ALTER COLUMN "progress_percent" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "work_packages" ALTER COLUMN "spent_hours" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "updated_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "sprints" ALTER COLUMN "created_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" ALTER COLUMN "lag_days" DROP NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66181ab26ce83746f858e62c34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_412f03f2a073c89f8918e6ae52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23c3961f60f0d66110d6b292ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3d5764d4b44970698381dc664"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TYPE "public"."activity_logs_entitytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activity_logs_actiontype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0441d95918d17f347cef513b9e"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22bd6c46545bb03821d08f282c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72bf9076541377ad54db20a359"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0d1a12bb5e099d982b5e14266"`);
        await queryRunner.query(`DROP TABLE "cost_entries"`);
        await queryRunner.query(`DROP TYPE "public"."cost_entries_type_enum"`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "time_entries_hours_check" CHECK ((hours > (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "valid_board_type" CHECK (((board_type)::text = ANY ((ARRAY['basic'::character varying, 'status'::character varying, 'team'::character varying, 'version'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "valid_scheduling" CHECK (((scheduling_mode)::text = ANY ((ARRAY['automatic'::character varying, 'manual'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "valid_priority" CHECK (((priority)::text = ANY ((ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "valid_type" CHECK (((type)::text = ANY ((ARRAY['task'::character varying, 'milestone'::character varying, 'phase'::character varying, 'feature'::character varying, 'bug'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "work_packages_progress_percent_check" CHECK (((progress_percent >= 0) AND (progress_percent <= 100)))`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "valid_sprint_dates" CHECK ((end_date >= start_date))`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "valid_sprint_status" CHECK (((status)::text = ANY ((ARRAY['planned'::character varying, 'active'::character varying, 'completed'::character varying, 'cancelled'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" ADD CONSTRAINT "valid_relation" CHECK (((relation_type)::text = ANY ((ARRAY['successor'::character varying, 'predecessor'::character varying, 'blocks'::character varying, 'blocked_by'::character varying, 'relates_to'::character varying, 'duplicates'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" ADD CONSTRAINT "no_self_relation" CHECK ((from_id <> to_id))`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "valid_phase" CHECK (((lifecycle_phase)::text = ANY ((ARRAY['initiation'::character varying, 'planning'::character varying, 'execution'::character varying, 'monitoring'::character varying, 'closure'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "valid_status" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'on_hold'::character varying, 'completed'::character varying, 'archived'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "valid_status" CHECK (((status)::text = ANY ((ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying])::text[])))`);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_role" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_user" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_group_members_group" ON "user_group_members" ("group_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_group_members_user" ON "user_group_members" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_role_permissions_permission" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "idx_role_permissions_role" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comments_created" ON "comments" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_comments_parent" ON "comments" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comments_user" ON "comments" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comments_entity" ON "comments" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "idx_time_date" ON "time_entries" ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_time_user" ON "time_entries" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_time_wp" ON "time_entries" ("work_package_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_sprint_burndown_sprint_date" ON "sprint_burndown" ("sprint_id", "date") `);
        await queryRunner.query(`CREATE INDEX "idx_sprint_burndown_date" ON "sprint_burndown" ("date") `);
        await queryRunner.query(`CREATE INDEX "idx_sprint_burndown_sprint" ON "sprint_burndown" ("sprint_id") `);
        await queryRunner.query(`CREATE INDEX "idx_boards_project" ON "boards" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_board_columns_position" ON "board_columns" ("board_id", "position") `);
        await queryRunner.query(`CREATE INDEX "idx_board_columns_board" ON "board_columns" ("board_id") `);
        await queryRunner.query(`CREATE INDEX "idx_baselines_project" ON "baselines" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bwp_work_package" ON "baseline_work_packages" ("work_package_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bwp_baseline" ON "baseline_work_packages" ("baseline_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_work_calendars_is_default" ON "work_calendars" ("is_default") `);
        await queryRunner.query(`CREATE INDEX "IDX_work_calendars_project_id" ON "work_calendars" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wp_dates" ON "work_packages" ("start_date", "due_date") `);
        await queryRunner.query(`CREATE INDEX "idx_wp_status" ON "work_packages" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_wp_parent" ON "work_packages" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wp_assignee" ON "work_packages" ("assignee_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wp_project" ON "work_packages" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_sprints_status" ON "sprints" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_sprints_project" ON "sprints" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wpr_to" ON "work_package_relations" ("to_id") `);
        await queryRunner.query(`CREATE INDEX "idx_wpr_from" ON "work_package_relations" ("from_id") `);
        await queryRunner.query(`CREATE INDEX "idx_portfolios_owner" ON "portfolios" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_programs_owner" ON "programs" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_programs_portfolio" ON "programs" ("portfolio_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_status" ON "projects" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_owner" ON "projects" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_portfolio" ON "projects" ("portfolio_id") `);
        await queryRunner.query(`CREATE INDEX "idx_projects_program" ON "projects" ("program_id") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_group_members" ADD CONSTRAINT "user_group_members_group_id_fkey" FOREIGN KEY ("group_id") REFERENCES "user_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_group_members" ADD CONSTRAINT "user_group_members_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_parent" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "fk_comments_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "fk_time_entries_work_package" FOREIGN KEY ("work_package_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_entries" ADD CONSTRAINT "fk_time_entries_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "fk_boards_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "board_columns" ADD CONSTRAINT "fk_board_columns_board" FOREIGN KEY ("board_id") REFERENCES "boards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "baselines" ADD CONSTRAINT "fk_baselines_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "baselines" ADD CONSTRAINT "fk_baselines_creator" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "baseline_work_packages" ADD CONSTRAINT "fk_bwp_baseline" FOREIGN KEY ("baseline_id") REFERENCES "baselines"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "FK_71743212b396e38a37c4ec09369" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "fk_work_packages_parent" FOREIGN KEY ("parent_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "fk_work_packages_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "fk_work_packages_accountable" FOREIGN KEY ("accountable_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_packages" ADD CONSTRAINT "fk_work_packages_assignee" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_package_watchers" ADD CONSTRAINT "fk_wpw_work_package" FOREIGN KEY ("work_package_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_package_watchers" ADD CONSTRAINT "fk_wpw_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" ADD CONSTRAINT "fk_wpr_to" FOREIGN KEY ("to_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_package_relations" ADD CONSTRAINT "fk_wpr_from" FOREIGN KEY ("from_id") REFERENCES "work_packages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolios" ADD CONSTRAINT "portfolios_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "programs_portfolio_id_fkey" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "programs" ADD CONSTRAINT "programs_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_program_id_fkey" FOREIGN KEY ("program_id") REFERENCES "programs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_portfolio_id_fkey" FOREIGN KEY ("portfolio_id") REFERENCES "portfolios"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "projects_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
